### ISSUE TITLE
CloudFrontを介してのアクセス時にCSRF認証が誤検出する問題を解消する

### ISSUE THREAD

**Issue by potato4d** [potato4d/contributter#3]
現在Contributterは `CloudFront -> LightSail(NGINX) -> Lightsail(Rails)` という流れでアクセスを受け取っている。NGINXサーバーはOriginサーバーとして動作し、HTTPS化のためにCloudFrontとは別のURLを指定している。

この際、CloudFront側のドメインは https://contributter.potato4d.me となるが、 Lightsail側は http://contributter-origin.potato4d.me となってしまい、CSRF認証において不整合が生じる。

この問題を解消するために、AWS側の設定を変える。もしくはNGINX側でヘッダーを改竄して送る必要がある。

あるいは、RailsのCSRF認証からOrigin認証を外すということもできるが、これは一時的な策以外で行いたくない。

これらについて、何かしらの形で解決策を検討、実施する。

**Comment by potato4d** [comment]
なお、現在は一時的に無理矢理動作させているため動く。

**Comment by potato4d** [comment]
https-portalがvolume指定をするとLE証明書を使いまわしてくれる可能性があるため、近日中に検証を行った上で、使いまわしてくれる場合はそもそもCFを外しても良い。

**Comment by ykzts** [comment]
[[新機能] Amazon CloudFrontでHostヘッダを転送する ｜ Developers.IO](https://dev.classmethod.jp/cloud/cloudfront-host-header-forward/) で解決しませんか?

**Comment by potato4d** [comment]
@ykzts 
ありがとうございます！見てみます :pray:

**Comment by potato4d** [comment]
Resolved.
