### ISSUE TITLE
contribution数が全て0になっている

### ISSUE THREAD

**Issue by eggplants** [potato4d/contributter#66]
2023/01/07のツイートより、contibution数が全て0になっています。

https://twitter.com/search?q=%23contributter_report%20until%3A2023-01-08%20since%3A2023-01-07&src=typed_query&f=live

**Comment by potato4d** [comment]
確認します。

**Comment by eggplants** [comment]
1441c39950dbe2c0c554348e374e81a118bbb397 により治ったように見えます。対応ありがとうございます。

https://twitter.com/search?q=%23contributter_report%20until%3A2023-01-09%20since%3A2023-01-08&src=typed_query&f=live
